FROM cimg/openjdk:8.0.272

# install basics
RUN cd ~ ; git clone https://github.com/SRI-CSL/daikon-gradle-plugin.git dgp
RUN cd ~/dgp ; ./gradlew clean; ./gradlew build; ./gradlew publishToMavenLocal


COPY . /usr/local/src/descert-example
WORKDIR /usr/local/src/descert-example

RUN ./gradlew clean
RUN ./gradlew build
RUN ./gradlew runDaikon

# STATUS
# Throws the following error when
# running the ./gradlew clean command
# Gradle could not start your build.
# > Could not create service of type CrossBuildFileHashCache using BuildSessionServices.createCrossBuildFileHashCache().
#    > Failed to create parent directory '/usr/local/src/descert-example/.gradle' when creating directory '/usr/local/src/descert-example/.gradle/6.7.1/fileHashes'
